theme: jekyll-theme-hacker

title: "My GitHub Stars"
description: "All my GitHub Stars. Repositorios geniales que he guardado en GitHub."
author: tutosrive

google_analytics: "G-Q8EY8DDPKP"

icon: "https://tutosrive.is-a.dev/db-nosql-2026-1/assets/icon.png"
image: "https://tutosrive.is-a.dev/db-nosql-2026-1/assets/preview.png"